theme: jekyll-theme-minimal
title: Plimpton 322
description: Es mi secreto a voces, mi portfolio dónde tengo planeado subir todos los proyetos que en algún momento llevé a cabo, o estoy llevando a cabo dentro de estos momentos.
